Repository mdsreq-fga-unb/2024.1-Nimbus, pull requests merged in 2024-04, with the labels that each got.

#7 [docs] Adicionar questionário na missão 1
  docs/missoes/missao1/questionario.md
Labels: documentation, chore

#22 [docs] .yml fixed
  mkdocs.yml
Labels: chore

#29 fix imagens
  docs/faccao/faccao.md
Labels: documentation, chore

#33 [chore] Adicionar Lições Aprendidas ao Pages
  docs/missoes/missao1/licoes-aprendidas.md
Labels: documentation, chore

#34 Fix processos
  docs/visao-geral/processo-desenvolvimento.md
  docs/visao-geral/visao-projeto.md
Labels: documentation, chore

#35 [chore] Multiple Chores have been done here
  docs/img/ishikawa.png
  docs/img/process_plan.jpeg
  docs/licoes-aprendidas.md
  docs/visao-geral/processo-desenvolvimento.md
  docs/visao-geral/visao-produto.md
Labels: documentation, chore

#36 [chore] Adicionar slides de fundamentos de ESW
  docs/img/fundamentos_esw/1.png
  docs/img/fundamentos_esw/10.png
  docs/img/fundamentos_esw/11.png
  docs/img/fundamentos_esw/12.png
  docs/img/fundamentos_esw/13.png
  docs/img/fundamentos_esw/14.png
  docs/img/fundamentos_esw/15.png
  docs/img/fundamentos_esw/16.png
  docs/img/fundamentos_esw/17.png
  docs/img/fundamentos_esw/2.png
  docs/img/fundamentos_esw/3.png
  docs/img/fundamentos_esw/4.png
  docs/img/fundamentos_esw/5.png
  docs/img/fundamentos_esw/6.png
  docs/img/fundamentos_esw/7.png
  docs/img/fundamentos_esw/8.png
  docs/img/fundamentos_esw/9.png
  docs/missoes/missao1/fundamentos.md
  mkdocs.yml
Labels: documentation, requirements, chore

#39 [fix] Correção de pequenos erros no PR anterior
  docs/faccao/faccao.md
  docs/index.md
  docs/visao-geral/visao-projeto.md
Labels: documentation, requirements, chore
